### ISSUE TITLE
Merge effort with vscode-reasonml?

### ISSUE THREAD

**Issue by chenglou** [hackwaly/vscode-ocaml#114]
Hello @hackwaly! I haven't noticed this plugin until now. I was wondering if you'd be interested joining effort with [vscode-reasonml](https://github.com/reasonml-editor/vscode-reasonml), which, despite the name, also supports ocaml already.

If not, feel free to close this issue! Thanks =)

**Comment by hackwaly** [comment]
I started this project for my own using as that time there's no good editor for ocaml. For now, vscode-reasonml may good than vscode-ocaml, and I have not enough idle time to continue develop this plugin. I'll tell the users to use vscode-reasonml in favor of vscode-ocaml at appropriate time (you can tell me). And if you have any request to me, it's welcome!

**Comment by chenglou** [comment]
I can promise that the quality of vscode-reasonml is solid! We use it daily for both OCaml and Reason syntax. I've submitted a PR to redirect folks to vscode-reasonml. It's a deprecation notice; if that's too much then I can change the wording to something else.

Thanks for the consideration =)

**Comment by hackwaly** [comment]
Does vscode-reasonml provide ocaml debugging support? Some of vscode-ocaml users are heavily relied on that feature.

**Comment by hackwaly** [comment]
Does vscode-reasonml provide ocaml debugging support? Some of vscode-ocaml users (include myself) are heavily relied on that feature.

**Comment by chenglou** [comment]
Aah good point, cc @freebroccolo

**Comment by ghost** [comment]
Hi @hackwaly, @chenglou,

I'd been thinking about suggesting some collaboration like this for awhile but hadn't gotten around to it since until recently I was just too busy with other projects, etc.

I think most of the main functionality of this plugin is available in vscode-reasonml now. But the big thing missing is indeed the debugging support. I've been a little reluctant to recommend people use the vscode-reasonml plugin for OCaml because of that, although it mostly works.

I never got to the debugger for a few reasons. One was because at the time I created the plugin, I wasn't sure what debugging tools people were going to use with Reason. Another is that I wasn't sure how the debugging functionality would be integrated with the language server. I haven't checked to see whether there is some sort of official support for that on the server side now or whether it will have to mostly be taken care of by the client part.

But anyway, I would be open to working together somehow. @hackwaly, I suppose the debugger as it currently exists here could be ported to the vscode-reasonml client as a first effort with credit to your great work here on this plugin. I could try to take a look at porting it but it may be awhile before I can get to it. If you or someone else wants to try sooner though, I would be happy to answer questions or provide whatever feedback is necessary to help out.

Another possibility, which might be a cleaner option, would be to keep this plugin separate, at least for the time being, and just remove the overlapping features (diagnostics stuff, etc.) but keep the debugger. At that point, we could set it up to where it gets installed as a dependency to the vscode-reasonml plugin automatically. Then we could take more time to consider the best way to integrate the debugger into the language server.

**Comment by hackwaly** [comment]
Hi @chenglou, @freebroccolo,

Yeah! I've decided to develop a standalone ocaml debug adapter which directly use ocaml debug protocol (see https://github.com/hackwaly/ocamlvsdebug) and deprecate this plugin some day. But I have no time to continue to develop it, at least for these months (I'm freelance and I have to make money to live). If you have interest in implementing debugger support, it can be a reference barely.

Yes, I think we create another debugging support plugin is a better option.

**Comment by hackwaly** [comment]
I've tasted reasonml-editor last night. It's not bad and it has active maintaining. The only missing is the debugger support. I'll split the debugger part of this extension to a separated extension **later**, and accept the deprecation pull request **now**. If someone really need some points  reasonml-editor doesn't have, he/she can still use this extension.

**Comment by tizoc** [comment]
I just tried the vscode-reasonml plugin, but had to revert back to the vscode-ocaml plugin.

I just tried it for a bit, but found some issues with very basic functionality:
- Type inference doesn't work as well as with this plugin (which is weird, both use merlin for that I guess), and gives me much more general type signatures.
- Doesn't highlight errors.

The deprecation notice is a bit confusing, because it makes it look like this plugin is unmaintained, or that the reasonml plugin is an instant replacement, which it isn't yet.

**Comment by donut** [comment]
@tizoc I'm having the same problem. Are you using `jbuilder` or some other build system that generates multiple `.merlin` files distributed in subdirectories instead of a single one in the root of your project? That seems to be the issue for me.

See https://github.com/reasonml-editor/vscode-reasonml/issues/76

I haven't found a good work around and that issue doesn't seem to be a priority for the vscode-reasonml dev.

**Comment by tizoc** [comment]
No, I'm not using jbuilder, I have a single `.merlin` file, which is not at the root of the project, but in the same directory where the OCaml code lives.

My problem seems to be the opposite as yours, I don't get reporting for any errors.

**Comment by donut** [comment]
@tizoc I don't get reporting for any errors either. The issue I linked to may cover multiple (related?) problems. You may actually have an easy solution: symlink your `.merlin` file to the root of your project.

**Comment by ghost** [comment]
> I haven't found a good work around and that issue doesn't seem to be a priority for the vscode-reasonml dev.

@donut I'm sorry if you've gotten the impression that issue or the others mentioned in this thread are not a priority for me. They are a priority, but please keep in mind that I currently work on the extension in my spare time. Sometimes that means issues do not get fixed as quickly as I would like. However, I am more than willing to accept PRs and answer questions.

Having said that, I am working on a new release as we speak that will have fixes for these and most of the other outstanding issues on the tracker. Hopefully it will be ready for release next week.

In the meantime, I'd suggest that if `vscode-ocaml` is working fine for you right now, there's no particular reason to switch.

**Comment by donut** [comment]
@freebroccolo I totally understand regarding priority. I did mean that as a slant towards you, just matter-of-factly. I assumed that the other more Reason-centric issues take priority.

That's great to hear regarding the new release. Really looking forward to it. Some things of `vscode-ocaml` have been bothering me and I am really looking forward to being able to use `vscode-reasonml`.

**Comment by donut** [comment]
With `vscode-reasonml` v1.0.8 my issues seem to be resolved. Really appreciate the much nicer type/doc info in the tooltips and more detailed syntax highlighting. I'll really dig into it later today.

**Comment by tizoc** [comment]
Just switched plugins to give `vscode-reasonml` another try, and the two issues I mentioned before have been resolved. Thank you @freebroccolo

**Comment by vogler** [comment]
I used both extensions up until now, but that duplicates symbols (outline, go to symbol etc.).
Would be nice if the debugger-part was integrated into vscode-reasonml, or if vscode-ocamldebug was available in the extension marketplace.
How do I install it from [this](https://github.com/hackwaly/ocamlvsdebug)?

**Comment by hackwaly** [comment]
No, vscode-ocamldebug is not finished. If you want to use debugging feature, just use this extension.

**Comment by hackwaly** [comment]
I've just finished the first version of my standalone OCaml debug adapter (purely written in OCaml).

![default](https://user-images.githubusercontent.com/540298/46250923-fbd51c00-c477-11e8-9feb-73e1265df899.gif)
