### ISSUE TITLE
Remote debugging

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#18]
Can you add an additional debug setting (I propose name "symbols") to make use of separate debug symbols (.cds) possible? Normally you just run `ocamldebug ocamlprog_executable`, `set loadingmode manual` and then start `ocamlprog_executable` as a separate process. But sometimes you need to debug embedded ocaml code and the main executable is not an ocaml program. In this case OCaml compiler is able to create debug & symbols info file (.cds). So you run `ocamldebug ocamlprog.cds` and then start `main_executable` when `ocamldebug` starts to wait for connection. To summarize, I see the following logic:

```
"symbols": missing or empty
"program": "path to ocaml executable",
```

 : normal mode: ocamldebug ${program}, launch ${program}

```
"symbols": "path to .cds file"
"program": "path to executable",
```

: embedded mode: ocamldebug ${symbols}, launch ${program}

```
"symbols": "path to .cds file"
"program": missing or empty
```

: remote mode: ocamldebug ${symbols}, wait for remote launch

In the latter case it would be great to see some notification ("ocamldebug is waiting for connection on x.x.x.x:xxxxx") so the user could know it's time to start the debugee. Is some sort of dialog window possible with VS Code?

**Comment by hackwaly** [comment]
Where can I get the documentation? I only found this http://caml.inria.fr/pub/docs/manual-ocaml/debugger.html. There's only "program", and no "symbols".

For remote/embedded debug support: You can set "program" to "path to *.cds file", and specify an option `"socket": "x.x.x.x:xxxxx"`. This will let extension only launch debugger listen to the socket, and just wait for you to launch debuggee with `CAML_DEBUG_SOCKET="x.x.x.x:xxxxx"` manually.

As you say, the socket ready message ("ocamldebug is waiting for connection on x.x.x.x:xxxxx") should be shown timely. This is missing and should be fixed in next version.

EDIT: Answer to your last question: No, if you mean a modal dialog, but can output a message. The debugger adapter process is separated from vscode ui process, and has a limited range of api to do debug related tasks.

**Comment by db4** [comment]
Well, my patch to OCaml implementing this feature was discussed in http://caml.inria.fr/mantis/view.php?id=4703. It's integrated into official distribution long time ago:

> Support for debugging of embedded applications has been committed in branch "release311".
> It is quite similar to the proposed patch, except that the name of the cds file is not saved in
> the executable. Instead, one should set the "CAML_DEBUG_FILE" environment variable
> (name chosen to be consistent with the "CAML_DEBUG_SOCKET" variable) to point to the
> aforementioned cds file.

but probably they forgot to update the docs?

**Comment by hackwaly** [comment]
So, "symbols" is needed as well, otherwise people will be confused.

**Comment by db4** [comment]
> So, "symbols" is needed as well, otherwise people will be confused.

You mean "symbols" setting? It's up to you. Personally I would make it optional as explained before. If you think "symbols" name is confusing, rename it to, say, "separate_symbols" or something like that.
