### ISSUE TITLE
Add OCaml toplevel support

### ISSUE THREAD

**Issue by db4** [hackwaly/vscode-ocaml#60]
Like [tuareg](https://github.com/ocaml/tuareg) or [OcaIDE](https://github.com/nbros/OcaIDE/blob/master/Ocaml.help/docs/tools/toplevel.html) do. An ability to launch [UTop](https://github.com/diml/utop) instead of the regular toplevel would be very good as well.

**Comment by hackwaly** [comment]
I haven't used utop before. Did you mean that provide a command to open a new integrated terminal session initialized with utop? And a command to send selection to the utop terminal session, etc.

**Comment by db4** [comment]
Well, as a first step it will be enough (the integrated terminal supports ANSI colors, doesn't it?). As a second step, more tight integration with `utop` can be implemented, like [utop Emacs mode](https://github.com/diml/utop/blob/master/src/top/utop.el). This way utop is launched with `-emacs`  command line option and implements a communication protocol with commands `input, input-multi, complete, history-prev, history-next, exit, save-history, require` Say, you can feed utop:

```
input:
data:let x = 1;;
end:
```

and you'll get:

```
accept:
prompt:
stdout:val x : int = 1
```

**Comment by hackwaly** [comment]
Since VS Code didn't have enough api(s) to achieve this. I can just implement a command that initiate a new utop session, nothing more than send a "utop\n" to a new terminal session, but it makes our extension requires vscode v1.5.0 as a minimal version.

For now, there's no api to peek if our utop terminal is hidden or destroyed (so we can't implement even "toggle" feature), and there's no api to integrate the utop like emacs unless we reimplement a terminal emulator use the vim extension way.

So, I decide to delay to implement this feature to when vscode provide enough api(s).

**Comment by db4** [comment]
OK, future full-scale utop support is interesting thing, but maybe we can implement basic ocaml toplevel support right now? The main feature currently missing is (for me) an ability to send line/selection/file from the active editor window to the toplevel process (running in a terminal window) for evaluation.

**Comment by hackwaly** [comment]
@db4 , You can try the [`utop`](https://github.com/hackwaly/vscode-ocaml/tree/utop) branch version.

**Comment by hackwaly** [comment]
As vscode exposes `window.onDidCloseTerminal` API in version 1.6.0, we can implement most features now.

**Comment by hackwaly** [comment]
Close this issue since v0.6.2 published.
