### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DemiMarie** [hackwaly/vscode-ocaml#96]
This repo lacks a license and so is unusable.  Please:

- choose a license
- get permission from all contributors to use their code under the license
- release vscode-ocaml under the license

**Comment by hackwaly** [comment]
Hi @DemiMarie, I don't have any experience on it. You can open an pull request to add open source license to this project. I'm very pleasure to accept that. 

Which license do you prefer? I'd like to make this project same license as merlin project, because most features of this extension is based on it.

**Comment by superherointj** [comment]
MIT :)

**Comment by pbsladek** [comment]
@hackwaly Merlin uses [MIT](https://github.com/ocaml/merlin/blob/master/LICENSE_MIT.txt)

Decent resource for the basics: [choosealicense.com](https://choosealicense.com/)
